codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
      qmongjs:
        paths:
          - packages/qmongjs
      skde:
        paths:
          - apps/skde
    patch:
      default:
        target: auto
        threshold: 5%

comment: false
