codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
      qmongjs:
        paths:
          - packages/qmongjs
        threshold: 5%
      skde:
        paths:
          - apps/skde
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%

comment: false

ignore:
  - "apps/skde/public/"
