codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
      qmongjs:
        paths:
          - packages/qmongjs
      skde:
        paths:
          - apps/skde

comment: false
