version: "3.6"

services:
  strapi:
    image: hnskde/mong-strapi:387-strapi-cms
    ports:
      - 1337:1337
    environment:
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      APP_KEYS: sadgfh
      ADMIN_JWT_SECRET: ecc72c04fa344bfa9889bcd2cc572036bd239ce305123fb70a003a8b7b84db52
      JWT_SECRET: 2d88f55a1288e0f8787eb935578dce5983873d6a8fd4b90c38896e6e32e63c54
      API_TOKEN_SALT: ewsdfgchg

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    ports:
      - "3306:3306"
