packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@mong/material-ui": true
  "@mui/x-telemetry": true
  cypress: true
  inotify: true
  sharp: true
minimumReleaseAgeExclude:
  - "@mong/material-ui"
  - '@turbo/darwin-64@2.10.0'
  - '@turbo/darwin-arm64@2.10.0'
  - '@turbo/linux-64@2.10.0'
  - '@turbo/linux-arm64@2.10.0'
  - '@turbo/windows-64@2.10.0'
  - '@turbo/windows-arm64@2.10.0'
  - turbo@2.10.0
