packages:
  - "apps/*"
  - "packages/*"
injectWorkspacePackages: true
allowBuilds:
  "@mong/material-ui": true
  "@mui/x-telemetry": true
  cypress: true
  sharp: true
minimumReleaseAgeExclude:
  - "@mong/material-ui"
