import { MongProvider } from "@mong/material-ui";
import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";


// Fonts will be included in MongProvider in the future
const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--color-brand-primary",
});

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en" className={roboto.variable}>
      <body
        className={`min-h-full  flex flex-col ${robotoSans.variable} ${robotoMono.variable} antialiased`}
      >
        <MongProvider>{children}</MongProvider>
      </body>
    </html>
  );
}
