import { LicenseInfo } from "@mui/x-license";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { useRouter } from "next/router";
import { NextAdapter } from "next-query-params";
import { useEffect, useState } from "react";
import { QueryParamProvider } from "use-query-params";
import "../app/global.css";
import "@mong/material-ui/index.css"; //Denne må nederst
import { PageContent, SkdePagesProvider } from "@mong/material-ui";
import type { AppProps } from "next/app";
import "@mong/material-ui/index.css";

import { Plus_Jakarta_Sans, Roboto, Roboto_Mono } from "next/font/google";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--color-brand-primary",
});

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const plus_jakarta_sans = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

function MyApp({ Component, pageProps }: AppProps) {
  const [queryClient] = useState(() => new QueryClient());
  const { pathname } = useRouter();
  const lang =
    pathname.includes("/en/") || pathname.endsWith("/en") ? "en" : "no";
  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  LicenseInfo.setLicenseKey(process.env.NEXT_PUBLIC_MUI_X_LICENSE_KEY || "");

  return (
    <main
      className={`min-h-full  flex flex-col ${plus_jakarta_sans.className} ${roboto.variable} ${robotoSans.variable} ${robotoMono.variable} antialiased`}
    >
      <SkdePagesProvider pageProps={pageProps}>
        <QueryParamProvider adapter={NextAdapter}>
          <QueryClientProvider client={queryClient}>
            <Component {...pageProps} />
            <ReactQueryDevtools initialIsOpen={false} />
          </QueryClientProvider>
        </QueryParamProvider>
      </SkdePagesProvider>
    </main>
  );
}

export default MyApp;
