const commonIndicators = [
  "hjerteinfarkt_reper_stemi_tid",
  "hjerneslag_beh_tromb",
  "NDV_andel_HbA1C_stoerre_eller_lik_75",
  "hoftebrudd_ventetid48",
  "hoftebrudd_stammefiks",
];

export const indicatorsPerHospital = [
  {
    unit: "Kirkenes",
    commonInd: commonIndicators,
    specificInd: [
      "hjerneslag_test_svelg",
      "hjerteinfarkt_invasivt_nstemi",
      "nyre_transplant_bt",
      "hjertesvikt_6min_gangtest",
    ],
  },
  {
    unit: "Hammerfest",
    commonInd: commonIndicators,
    specificInd: ["barnediabetes_hba1c_ge_9", "NDV_prosentandel_maalt_AKR"],
  },
  {
    unit: "Tromsø",
    commonInd: commonIndicators,
    specificInd: ["hjerneslag_test_svelg"],
  },
  {
    unit: "Harstad",
    commonInd: commonIndicators,
    specificInd: [
      "nger_kompl_intra_hys",
      "norgast_lekkasje_tykktarm",
      "norgast_saarruptur",
    ],
  },
  {
    unit: "Narvik",
    commonInd: commonIndicators,
    specificInd: ["hjerteinfarkt_ef_maalt", "NDV_prosentandel_maalt_AKR"],
  },
  {
    unit: "Vesterålen",
    commonInd: commonIndicators,
    specificInd: ["hjerneslag_test_svelg", "hjerteinfarkt_ef_maalt"],
  },
  {
    unit: "Bodø",
    commonInd: commonIndicators,
    specificInd: [
      "NDV_andel_oppnaadd_kolesterolmaal_med_hjertekarsykdom",
      "norgast_lekkasje_tykktarm",
      "nger_kompl_intra_hys",
    ],
  },
  {
    unit: "Lofoten",
    commonInd: commonIndicators,
    specificInd: ["hjerteinfarkt_ef_maalt", "hjerneslag_test_svelg"],
  },
  {
    unit: "Mo i Rana",
    commonInd: commonIndicators,
    specificInd: ["hjerneslag_test_svelg", "hjertesvikt_6min_gangtest"],
  },
  {
    unit: "Mosjøen",
    commonInd: commonIndicators,
    specificInd: [
      "NDV_andel_HbA1C_mindre_eller_lik_53",
      "NDV_andel_oppnaadd_kolesterolmaal_med_hjertekarsykdom",
      "NDV_andel_oppnaadd_kolesterolmaal_uten_hjertekarsykdom",
      "NDV_prosentandel_maalt_AKR",
    ],
  },
  {
    unit: "Sandnessjøen",
    commonInd: commonIndicators,
    specificInd: [
      "hjerneslag_tverrfaglig",
      "traume_registrerte",
      "NDV_prosentandel_maalt_AKR",
      "NDV_andel_oppnaadd_kolesterolmaal_uten_hjertekarsykdom",
      "nnrr_tverrfaglig_behandling",
    ],
  },
];

export const indicatorInfo = [
  {
    indId: "hjerteinfarkt_reper_stemi_tid",
    title: "Reperfusjonsbehandling innen anbefalt tid ved STEMI",
    include: 1,
    sformat: ",.0%",
    level_green: 0.85,
    level_yellow: 0.7,
    level_direction: 1,
    registry: "Hjerteinfarkt",
  },
  {
    indId: "hjerneslag_beh_tromb",
    title: "Andel behandlet med trombolyse",
    include: 1,
    sformat: ",.0%",
    level_green: 0.195,
    level_yellow: 0.13,
    level_direction: 1,
    registry: "Hjerneslag",
  },
  {
    indId: "NDV_andel_HbA1C_stoerre_eller_lik_75",
    title: "Andel med HbA1C ≥ 75 mmol/mol",
    include: 1,
    sformat: ",.0%",
    level_green: 0.12,
    level_yellow: 0.14,
    level_direction: 0,
    registry: "Voksendiabetes",
  },
  {
    indId: "hoftebrudd_ventetid48",
    title: "Operasjon innen 48 timer",
    include: 1,
    sformat: ",.0%",
    level_green: 0.9,
    level_yellow: 0.8,
    level_direction: 1,
    registry: "Hoftebrudd",
  },
  {
    indId: "hoftebrudd_stammefiks",
    title: "Sementert stamme ved bruk av protese",
    include: 1,
    sformat: ",.0%",
    level_green: 0.9,
    level_yellow: 0.8,
    level_direction: 1,
    registry: "Hoftebrudd",
  },
  {
    indId: "hjerneslag_test_svelg",
    title: "Andel som har fått vurdert/testet svelgefunksjon",
    include: 1,
    sformat: ",.0%",
    level_green: 0.95,
    level_yellow: 0.845,
    level_direction: 1,
    registry: "Hjerneslag",
  },
  {
    indId: "hjerteinfarkt_invasivt_nstemi",
    title: "	Koronar angiografi ved NSTEMI",
    include: 1,
    sformat: ",.0%",
    level_green: 0.85,
    level_yellow: 0.7,
    level_direction: 1,
    registry: "Hjerteinfarkt",
  },
  {
    indId: "nyre_transplant_bt",
    title: "Blodtrykk <130/80 (transplantasjon)",
    include: 1,
    sformat: ",.0%",
    level_green: 0.8,
    level_yellow: 0.7,
    level_direction: 1,
    registry: "Nyre",
  },
  {
    indId: "nger_kompl_intra_hys",
    title: "Hysteroskopi: Komplikasjoner under operasjonen",
    include: 1,
    sformat: ",.1%",
    level_green: 0.02,
    level_yellow: 0.04,
    level_direction: 0,
    registry: "Gynekologisk endoskopi",
  },
  {
    indId: "norgast_lekkasje_tykktarm",
    title:
      "Reseksjoner av tykktarm (kolon): Lekkasje fra skjøt (anastomoselekkasje)",
    sformat: ",.1%",
    include: 1,
    level_green: 0.04,
    level_yellow: 0.06,
    level_direction: 0,
    registry: "Gastrokirurgi",
  },
  {
    indId: "norgast_saarruptur",
    title: "Sårruptur",
    include: 1,
    sformat: ",.1%",
    level_green: 0.03,
    level_yellow: 0.04,
    level_direction: 0,
    registry: "Gastrokirurgi",
  },
  {
    indId: "hjerteinfarkt_ef_maalt",
    title: "Ejeksjonsfraksjon (EF) målt",
    include: 1,
    sformat: ",.0%",
    level_green: 0.8,
    level_yellow: 0.6,
    level_direction: 1,
    registry: "Hjerteinfarkt",
  },
  {
    indId: "NDV_andel_oppnaadd_kolesterolmaal_med_hjertekarsykdom",
    title:
      "Andel pasienter med kjent hjerte/karsykdom som har oppnådd kolesterolmål, LDL mindre enn 1,8 mmol/L ",
    include: 1,
    sformat: ",.0%",
    level_green: 0.6,
    level_yellow: 0.45,
    level_direction: 1,
    registry: "Voksendiabetes",
  },
  {
    indId: "NDV_andel_HbA1C_mindre_eller_lik_53",
    title: "Andel med HbA1C ≤ 53 mmol/mol",
    include: 1,
    sformat: ",.0%",
    level_green: 0.32,
    level_yellow: 0.29,
    level_direction: 1,
    registry: "Voksendiabetes",
  },
  {
    indId: "hjerneslag_tverrfaglig",
    title:
      "Andel pasienter med tverrfaglig funksjonsvurdering innen anbefalt tid",
    include: 1,
    sformat: ",.0%",
    level_green: 0.8,
    level_yellow: 0.7,
    level_direction: 1,
    registry: "Hjerneslag",
  },
  {
    indId: "traume_registrerte",
    title: "Antall registrerte",
    include: 1,
    sformat: ",.0%",
    level_green: 0.8,
    level_yellow: 0.6,
    level_direction: 1,
    registry: "Traume",
  },
  {
    indId: "NDV_prosentandel_maalt_AKR",
    title: "Prosentandel som har fått målt U-AKR",
    include: 1,
    sformat: ",.0%",
    level_green: 0.9,
    level_yellow: 0.7,
    level_direction: 1,
    registry: "Voksendiabetes",
  },
  {
    indId: "barnediabetes_hba1c_ge_9",
    title: "Andel HbA1c ≥ 75 mmol/mol",
    include: 1,
    sformat: ",.0%",
    level_green: 0,
    level_yellow: 0.02,
    level_direction: 0,
    registry: "Barne- og ungdomsdiabetes",
  },
  {
    indId: "hjertesvikt_6min_gangtest",
    title: "Andel utført 6-minutter gangtest",
    include: 1,
    sformat: ",.0%",
    level_green: 0.8,
    level_yellow: 0.7,
    level_direction: 1,
    registry: "Hjertesvikt",
  },
  {
    indId: "NDV_andel_oppnaadd_kolesterolmaal_uten_hjertekarsykdom",
    title:
      "Andel pasienter uten kjent hjerte/karsykdom som har oppnådd kolesterolmål, LDL mindre eller lik 2,5 mmol/L",
    include: 1,
    sformat: ",.0%",
    level_green: 0.7,
    level_yellow: 0.45,
    level_direction: 1,
    registry: "Voksendiabetes",
  },
  {
    indId: "nnrr_tverrfaglig_behandling",
    title: "Andel pasienter med tverrfaglig behandling",
    include: 1,
    sformat: ",.0%",
    level_green: 0.3,
    level_yellow: 0.3,
    level_direction: 1,
    registry: "Nakke- og rygg",
  },
];
