name: Node.js CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop, dependency_updates]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_HOST: https://prod-api.skde.org
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      # For now this is a private (gabrio.frantzen@bouvet.no) token for the npm registry, replace with organization token when we have that set up
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v6
      
      # Migrate to pnpm, remove lines that are commented out when it works !
      # - name: Enable Corepack before setting up Node
      #   run: corepack enable
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.1.3
            
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm format
      - run: pnpm check
      - run: pnpm knip
      - run: pnpm run test

      - name: Code coverage
        if: matrix.node-version == '22.x'
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
